name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build App
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

