name: Android Feature Branch CI

on:
  push:
    branches:
      - 'feature/*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Spotless Apply
        run: ./gradlew :spotlessApply

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

  upload_report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Jacoco Test Report
        run: ./gradlew jacocoTestReport

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Jacoco Test Reports
          path: |
            /home/runner/work/stargazer/stargazer/features/bookmarks/build/reports/jacoco/jacocoTestReport/html
            /home/runner/work/stargazer/stargazer/features/browse/build/reports/jacoco/jacocoTestReport/html
            /home/runner/work/stargazer/stargazer/features/repo-details/build/reports/jacoco/jacocoTestReport/html
            /home/runner/work/stargazer/stargazer/repository/build/reports/jacoco/jacocoTestReport/html

      - name: Upload Test Report
        run: |
          bash <(curl -s https://codecov.io/bash) -f "/home/runner/work/stargazer/stargazer/features/bookmarks/build/reports/jacoco/jacocoTestReport/html/index.html"
          bash <(curl -s https://codecov.io/bash) -f "/home/runner/work/stargazer/stargazer/stargazer/features/browse/build/reports/jacoco/jacocoTestReport/html/index.html"
          bash <(curl -s https://codecov.io/bash) -f "/home/runner/work/stargazer/stargazer/stargazer/features/repo-details/build/reports/jacoco/jacocoTestReport/html/index.html"
          bash <(curl -s https://codecov.io/bash) -f "/home/runner/work/stargazer/stargazer/stargazer/repository/build/reports/jacoco/jacocoTestReport/html/index.html"