name: Android Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Spotless
        run: /gradlew spotlessCheck

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
