name: Android Feature Branch CI

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Spotless Apply
        run: ./gradlew :spotlessApply

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Generate Jacoco Test Report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          fail_ci_if_error: true
          verbose: true