name: Build

on:
  pull_request: {}
  push:
    branches:
      - '*'

jobs:
  unitTest:
    name: Lint Check and Unit Test

    # Define environment to run on
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Project
        run: ./gradlew build

      - name: Run Android Linter
        run: ./gradlew lintDebug

      - name: Unit tests
        run: bash ./gradlew test --stacktrace